### ISSUE TITLE
Do something. Anything

### ISSUE THREAD

**Issue by ideabrian** [ntakouris/LearningPhaser#1]
Something needs to get started.

**Comment by ideabrian** [comment]
Do something. Anything. Good motto.

**Comment by ntakouris** [comment]
@ideabrian there's a full on game on the repo if you haven't noticed :)
About the FCC thing, I have kindof abandoned hope in webdev (frontend at least). I am doing some games with unreal and unity, as well as some apps on the play store. I may come back now that I just got into CS uni because I really need to get my java sever (wildfly) things going :)
